### ISSUE TITLE
Gültig ab & Gültig bis können nicht gelöscht werden

### ISSUE THREAD

**Issue by Voodoopupp** [hetfield74/MITS_ImageSlider#1]
Wenn man einmal in einem Slider eines der beiden Felder genutzt bzw. belegt hat, kann man dieses nachträglich nicht mehr entfernen. Beim Abspeichern wird immer wieder das zuletzt eingetragene Datum beibehalten.

**Comment by hetfield74** [comment]
Das Problem ist in Version v2.09 behoben
